_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.12.2
            "5": 0.18.7
            "8":
                - 1
                - 5
            "10":
                - 2
            "12": 0.18.7
            "13": linux-x86_64
dataset:
    value: MNIST
learning_rate:
    value: 0.0005
